name: Lint Workflow

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint Code with Flake8
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Instalar Flake8
      - name: Install Flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      # 4. Ejecutar Flake8
      - name: Run Flake8
        run: flake8 .
