# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

class TestTestselenium():
  def setup_method(self, method):
    # Set up Chrome options and specify the binary location
        options = webdriver.ChromeOptions()
        options.binary_location = "/usr/bin/google-chrome"  # Explicitly set the Chrome binary location

        # Use ChromeDriverManager to automatically manage driver installation
        self.driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
        self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testselenium(self):
    self.driver.get("http://127.0.0.1:5000/login")
    time.sleep(2)
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-dark").click()
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "My profile").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("hola")
    self.driver.find_element(By.ID, "confirm_password").click()
    self.driver.find_element(By.ID, "confirm_password").send_keys("hola")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-dark").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nav-link:nth-child(1)").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("hola")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-dark").click()
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "My profile").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.ID, "confirm_password").click()
    self.driver.find_element(By.ID, "confirm_password").send_keys("1234")
    self.driver.find_element(By.ID, "submit").click()

    self.driver.find_element(By.CSS_SELECTOR, ".text-dark").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nav-link:nth-child(1)").click()

    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.ID, "submit").click()