# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCreatenotepad():
    def setup_method(self, method):
        # Set up Chrome options and specify the binary location
        options = webdriver.ChromeOptions()
        options.binary_location = "/usr/bin/google-chrome"  # Explicitly set the Chrome binary location

        # Use ChromeDriverManager to automatically manage driver installation
        self.driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
        self.vars = {}
  
    def teardown_method(self, method):
        # Quit the driver after each test
        self.driver.quit()
  
    def test_createnotepad(self):
        # Open the login page
        self.driver.get("http://localhost:5000/login")
        time.sleep(2)

        # Set window size
        self.driver.set_window_size(912, 1011)

        # Log in using the form
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
        self.driver.find_element(By.ID, "password").send_keys("1234")
        self.driver.find_element(By.ID, "submit").click()
        time.sleep(2)

        # Navigate to the notepad creation page
        self.driver.get("http://localhost:5000/notepad/create")
        time.sleep(2)

        # Fill in the notepad form
        self.driver.find_element(By.ID, "title").click()
        self.driver.find_element(By.ID, "title").send_keys("n1")
        self.driver.find_element(By.ID, "body").click()
        self.driver.find_element(By.ID, "body").send_keys("n1")
        
        # Submit the form
        self.driver.find_element(By.ID, "submit").click()
