name: Lint Workflow

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - hotfix/#72-workflows-integration

jobs:
  lint:
    name: Lint Code with Flake8
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Instalar Flake8
      - name: Install Flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      # 4. Ejecutar Flake8 y capturar errores
      - name: Run Flake8
        continue-on-error: true  # No marca como fallo el paso
        run: |
          flake8 . --exclude=migrations/ > flake8-report.txt || true

      # 5. Subir el informe de errores
      - name: Upload Flake8 Report
        uses: actions/upload-artifact@v3
        with:
          name: flake8-report
          path: flake8-report.txt
