name: Run Tests

# Activadores: Ejecutar el workflow cuando se suban cambios o se abra un PR
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout del repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  

    # 3. Instalar dependencias
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    # 4. Ejecutar pruebas
    - name: Run tests
      run: |
        source venv/bin/activate
        pytest --maxfail=5 --disable-warnings

    # 5. Generar reporte de cobertura
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: htmlcov/ 
